### ISSUE TITLE
Unable to parse json when bootstrapping

### ISSUE THREAD

**Issue by MyMirelHub** [TykTechnologies/tyk-helm-chart#10]
I have an issue when trying to boostrap the dashboard. Using the shell script provided I get a JSON parsing error. 

```
$ ./tyk-pro/scripts/bootstrap_k8s.sh $NODE_IP:$NODE_PORT 12345 tyk

Creating Organisation
ORG DATA: {"Status":"OK","Message":"Org created","Meta":"5cd2ed7bff21b20001ad8d46"}
ORG ID: 5cd2ed7bff21b20001ad8d46

Adding new user
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 35 (char 34)
ERROR: Unable to parse JSON
```

**Comment by asoorm** [comment]
Just to check @MyMirelHub was this issue closed because you were using gitbash / windows on host machine to execute the shell script?
